#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
wizink:
  source:
      url: https://www.anapioficeandfire.com/api
